spring:
  application:
    name: demo-auth

  profiles:
    active: dev

  datasource:
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false

server:
  port: 81
  servlet:
    context-path: /

base:
  url: api/v1/demo/auth
